import type * as Types from '@/types';

// Default values for settings - Shared between Electron and Web
export const SETTINGS_DEFAULTS: Types.SystemSettings = {
  autoLogin: false,
  autoLaunch: false,
  alwaysOnTop: false,
  statusAutoIdle: false,
  statusAutoIdleMinutes: 10,
  statusAutoDnd: false,
  channelUIMode: 'classic',
  closeToTray: false,
  font: '',
  fontSize: 13,
  inputAudioDevice: '',
  outputAudioDevice: '',
  recordFormat: 'wav',
  recordSavePath: '',
  mixEffect: false,
  mixEffectType: '',
  autoMixSetting: false,
  echoCancellation: false,
  noiseCancellation: false,
  microphoneAmplification: false,
  manualMixMode: false,
  mixMode: 'all',
  speakingMode: 'auto',
  defaultSpeakingKey: '',
  notSaveMessageHistory: true,
  hotKeyOpenMainWindow: '',
  hotKeyScreenshot: '',
  hotKeyIncreaseVolume: '',
  hotKeyDecreaseVolume: '',
  hotKeyToggleSpeaker: '',
  hotKeyToggleMicrophone: '',
  disableAllSoundEffect: false,
  enterVoiceChannelSound: true,
  leaveVoiceChannelSound: true,
  startSpeakingSound: true,
  stopSpeakingSound: true,
  receiveDirectMessageSound: true,
  receiveChannelMessageSound: true,
  autoCheckForUpdates: true,
  updateCheckInterval: 60000,
  updateChannel: 'latest',
};
