/* eslint-disable @typescript-eslint/no-require-imports */
const { contextBridge, ipcRenderer } = require('electron');

const ipcEventEmitterHandlers = {
    send: ipcRenderer.send.bind(ipcRenderer),
    sendSync: ipcRenderer.sendSync.bind(ipcRenderer),
    invoke: ipcRenderer.invoke.bind(ipcRenderer),
    on: ipcRenderer.on.bind(ipcRenderer),
    removeListener: ipcRenderer.removeListener.bind(ipcRenderer),
};

const ipcRendererHandlers = {
    ipcEventEmitter: ipcEventEmitterHandlers,
    socketSend: (event, ...args) => ipcRenderer.send(event, ...args),
    socketEmit: (event, payload) => ipcRenderer.invoke(event, payload),
    getInitialData: (id) => ipcRenderer.sendSync(`get-initial-data?id=${id}`),
    errorSubmit: (errorId, error) => ipcRenderer.send('error-submit', errorId, error),
    exit: () => ipcRenderer.send('exit'),
    windowControlMinimize: () => ipcRenderer.send('window-control-minimize'),
    windowControlMaximize: () => ipcRenderer.send('window-control-maximize'),
    windowControlUnmaximize: () => ipcRenderer.send('window-control-unmaximize'),
    windowControlClose: () => ipcRenderer.send('window-control-close'),
    openPopup: (type, id, initialData, force) => ipcRenderer.send('open-popup', type, id, initialData, force),
    closePopup: (id) => ipcRenderer.send('close-popup', id),
    closeAllPopups: () => ipcRenderer.send('close-all-popups'),
    popupSubmit: (to, data) => ipcRenderer.send('popup-submit', to, data),
    addAccount: (account, data) => ipcRenderer.send('add-account', account, data),
    deleteAccount: (account) => ipcRenderer.send('delete-account', account),
    setLanguage: (language) => ipcRenderer.send('set-language', language),
    addCustomTheme: (theme) => ipcRenderer.send('add-custom-theme', theme),
    deleteCustomTheme: (index) => ipcRenderer.send('delete-custom-theme', index),
    setCurrentTheme: (theme) => ipcRenderer.send('set-current-theme', theme),
    updateDiscordPresence: (presence) => ipcRenderer.send('update-discord-presence', presence),
    saveRecord: (record) => ipcRenderer.send('save-record', record),
    setTrayTitle: (title) => ipcRenderer.send('set-tray-title', title),
    dontShowDisclaimerNextTime: () => ipcRenderer.send('dont-show-disclaimer-next-time'),
    checkForUpdates: () => ipcRenderer.send('check-for-updates'),
    changeServer: (server) => ipcRenderer.send('change-server', server),
    setAutoLogin: (enable) => ipcRenderer.send('set-auto-login', enable),
    setAutoLaunch: (enable) => ipcRenderer.send('set-auto-launch', enable),
    setAlwaysOnTop: (enable) => ipcRenderer.send('set-always-on-top', enable),
    setStatusAutoIdle: (enable) => ipcRenderer.send('set-status-auto-idle', enable),
    setStatusAutoIdleMinutes: (minutes) => ipcRenderer.send('set-status-auto-idle-minutes', minutes),
    setStatusAutoDnd: (enable) => ipcRenderer.send('set-status-auto-dnd', enable),
    setChannelUIMode: (mode) => ipcRenderer.send('set-channel-ui-mode', mode),
    setCloseToTray: (enable) => ipcRenderer.send('set-close-to-tray', enable),
    setFont: (font) => ipcRenderer.send('set-font', font),
    setFontSize: (fontSize) => ipcRenderer.send('set-font-size', fontSize),
    setInputAudioDevice: (deviceId) => ipcRenderer.send('set-input-audio-device', deviceId),
    setOutputAudioDevice: (deviceId) => ipcRenderer.send('set-output-audio-device', deviceId),
    setRecordFormat: (format) => ipcRenderer.send('set-record-format', format),
    setRecordSavePath: (path) => ipcRenderer.send('set-record-save-path', path),
    setMixEffect: (enabled) => ipcRenderer.send('set-mix-effect', enabled),
    setMixEffectType: (key) => ipcRenderer.send('set-mix-effect-type', key),
    setAutoMixSetting: (enabled) => ipcRenderer.send('set-auto-mix-setting', enabled),
    setEchoCancellation: (enabled) => ipcRenderer.send('set-echo-cancellation', enabled),
    setNoiseCancellation: (enabled) => ipcRenderer.send('set-noise-cancellation', enabled),
    setMicrophoneAmplification: (enabled) => ipcRenderer.send('set-microphone-amplification', enabled),
    setManualMixMode: (enabled) => ipcRenderer.send('set-manual-mix-mode', enabled),
    setMixMode: (key) => ipcRenderer.send('set-mix-mode', key),
    setSpeakingMode: (key) => ipcRenderer.send('set-speaking-mode', key),
    setDefaultSpeakingKey: (key) => ipcRenderer.send('set-default-speaking-key', key),
    setNotSaveMessageHistory: (enabled) => ipcRenderer.send('set-not-save-message-history', enabled),
    setHotKeyOpenMainWindow: (key) => ipcRenderer.send('set-hot-key-open-main-window', key),
    setHotKeyIncreaseVolume: (key) => ipcRenderer.send('set-hot-key-increase-volume', key),
    setHotKeyDecreaseVolume: (key) => ipcRenderer.send('set-hot-key-decrease-volume', key),
    setHotKeyToggleSpeaker: (key) => ipcRenderer.send('set-hot-key-toggle-speaker', key),
    setHotKeyToggleMicrophone: (key) => ipcRenderer.send('set-hot-key-toggle-microphone', key),
    setDisableAllSoundEffect: (enabled) => ipcRenderer.send('set-disable-all-sound-effect', enabled),
    setEnterVoiceChannelSound: (enabled) => ipcRenderer.send('set-enter-voice-channel-sound', enabled),
    setLeaveVoiceChannelSound: (enabled) => ipcRenderer.send('set-leave-voice-channel-sound', enabled),
    setStartSpeakingSound: (enabled) => ipcRenderer.send('set-start-speaking-sound', enabled),
    setStopSpeakingSound: (enabled) => ipcRenderer.send('set-stop-speaking-sound', enabled),
    setReceiveDirectMessageSound: (enabled) => ipcRenderer.send('set-receive-direct-message-sound', enabled),
    setReceiveChannelMessageSound: (enabled) => ipcRenderer.send('set-receive-channel-message-sound', enabled),
    setAutoCheckForUpdates: (enabled) => ipcRenderer.send('set-auto-check-for-updates', enabled),
    setUpdateCheckInterval: (interval) => ipcRenderer.send('set-update-check-interval', interval),
    setUpdateChannel: (channel) => ipcRenderer.send('set-update-channel', channel),
    cancelNetworkDiagnosis: () => ipcRenderer.send('cancel-network-diagnosis'),
    requestSfuDiagnosis: () => ipcRenderer.send('request-sfu-diagnosis'),
    sfuDiagnosisResponse: (data) => ipcRenderer.send('sfu-diagnosis-response', data),
    authLogin: (formData) => ipcRenderer.invoke('auth-login', formData),
    authLogout: () => ipcRenderer.invoke('auth-logout'),
    authRegister: (formData) =>
        ipcRenderer.invoke('auth-register', formData),
    authAutoLogin: (token) => ipcRenderer.invoke('auth-auto-login', token),
    dataUser: (params) => ipcRenderer.invoke('data-user', params),
    dataUserHotReload: (params) => ipcRenderer.invoke('data-user-hot-reload', params),
    dataFriend: (params) => ipcRenderer.invoke('data-friend', params),
    dataFriends: (params) => ipcRenderer.invoke('data-friends', params),
    dataFriendActivities: (params) => ipcRenderer.invoke('data-friendActivities', params),
    dataFriendGroup: (params) => ipcRenderer.invoke('data-friendGroup', params),
    dataFriendGroups: (params) => ipcRenderer.invoke('data-friendGroups', params),
    dataFriendApplication: (params) => ipcRenderer.invoke('data-friendApplication', params),
    dataFriendApplications: (params) => ipcRenderer.invoke('data-friendApplications', params),
    dataServer: (params) => ipcRenderer.invoke('data-server', params),
    dataServers: (params) => ipcRenderer.invoke('data-servers', params),
    dataServerMembers: (params) => ipcRenderer.invoke('data-serverMembers', params),
    dataServerOnlineMembers: (params) => ipcRenderer.invoke('data-serverOnlineMembers', params),
    dataChannel: (params) => ipcRenderer.invoke('data-channel', params),
    dataChannels: (params) => ipcRenderer.invoke('data-channels', params),
    dataChannelMembers: (params) => ipcRenderer.invoke('data-channelMembers', params),
    dataMember: (params) => ipcRenderer.invoke('data-member', params),
    dataMemberApplication: (params) => ipcRenderer.invoke('data-memberApplication', params),
    dataMemberApplications: (params) => ipcRenderer.invoke('data-memberApplications', params),
    dataMemberInvitation: (params) => ipcRenderer.invoke('data-memberInvitation', params),
    dataMemberInvitations: (params) => ipcRenderer.invoke('data-memberInvitations', params),
    dataNotifications: (params) => ipcRenderer.invoke('data-notifications', params),
    dataAnnouncements: (params) => ipcRenderer.invoke('data-announcements', params),
    dataRecommendServers: (params) => ipcRenderer.invoke('data-recommendServers', params),
    dataUploadImage: (params) => ipcRenderer.invoke('data-uploadImage', params),
    dataSearchServer: (params) => ipcRenderer.invoke('data-searchServer', params),
    dataSearchUser: (params) => ipcRenderer.invoke('data-searchUser', params),
    saveImage: (buffer, directory, filenamePrefix, extension) =>
        ipcRenderer.invoke('save-image', buffer, directory, filenamePrefix, extension),
    selectRecordSavePath: () => ipcRenderer.invoke('select-record-save-path'),
    enableLoopbackAudio: () => ipcRenderer.invoke('enable-loopback-audio'),
    disableLoopbackAudio: () => ipcRenderer.invoke('disable-loopback-audio'),
    runNetworkDiagnosis: (params) => ipcRenderer.invoke('run-network-diagnosis', params),
    getAccounts: () => ipcRenderer.sendSync('get-accounts'),
    getLanguage: () => ipcRenderer.sendSync('get-language'),
    getCustomThemes: () => ipcRenderer.sendSync('get-custom-themes'),
    getCurrentTheme: () => ipcRenderer.sendSync('get-current-theme'),
    getFontList: () => ipcRenderer.sendSync('get-font-list'),
    getSystemSettings: () => ipcRenderer.sendSync('get-system-settings'),
    getAutoLogin: () => ipcRenderer.sendSync('get-auto-login'),
    getAutoLaunch: () => ipcRenderer.sendSync('get-auto-launch'),
    getAlwaysOnTop: () => ipcRenderer.sendSync('get-always-on-top'),
    getStatusAutoIdle: () => ipcRenderer.sendSync('get-status-auto-idle'),
    getStatusAutoIdleMinutes: () => ipcRenderer.sendSync('get-status-auto-idle-minutes'),
    getStatusAutoDnd: () => ipcRenderer.sendSync('get-status-auto-dnd'),
    getChannelUIMode: () => ipcRenderer.sendSync('get-channel-ui-mode'),
    getCloseToTray: () => ipcRenderer.sendSync('get-close-to-tray'),
    getFont: () => ipcRenderer.sendSync('get-font'),
    getFontSize: () => ipcRenderer.sendSync('get-font-size'),
    getInputAudioDevice: () => ipcRenderer.sendSync('get-input-audio-device'),
    getOutputAudioDevice: () => ipcRenderer.sendSync('get-output-audio-device'),
    getRecordFormat: () => ipcRenderer.sendSync('get-record-format'),
    getRecordSavePath: () => ipcRenderer.sendSync('get-record-save-path'),
    getMixEffect: () => ipcRenderer.sendSync('get-mix-effect'),
    getMixEffectType: () => ipcRenderer.sendSync('get-mix-effect-type'),
    getAutoMixSetting: () => ipcRenderer.sendSync('get-auto-mix-setting'),
    getEchoCancellation: () => ipcRenderer.sendSync('get-echo-cancellation'),
    getNoiseCancellation: () => ipcRenderer.sendSync('get-noise-cancellation'),
    getMicrophoneAmplification: () => ipcRenderer.sendSync('get-microphone-amplification'),
    getManualMixMode: () => ipcRenderer.sendSync('get-manual-mix-mode'),
    getMixMode: () => ipcRenderer.sendSync('get-mix-mode'),
    getSpeakingMode: () => ipcRenderer.sendSync('get-speaking-mode'),
    getDefaultSpeakingKey: () => ipcRenderer.sendSync('get-default-speaking-key'),
    getNotSaveMessageHistory: () => ipcRenderer.sendSync('get-not-save-message-history'),
    getHotKeyOpenMainWindow: () => ipcRenderer.sendSync('get-hot-key-open-main-window'),
    getHotKeyIncreaseVolume: () => ipcRenderer.sendSync('get-hot-key-increase-volume'),
    getHotKeyDecreaseVolume: () => ipcRenderer.sendSync('get-hot-key-decrease-volume'),
    getHotKeyToggleSpeaker: () => ipcRenderer.sendSync('get-hot-key-toggle-speaker'),
    getHotKeyToggleMicrophone: () => ipcRenderer.sendSync('get-hot-key-toggle-microphone'),
    getDisableAllSoundEffect: () => ipcRenderer.sendSync('get-disable-all-sound-effect'),
    getEnterVoiceChannelSound: () => ipcRenderer.sendSync('get-enter-voice-channel-sound'),
    getLeaveVoiceChannelSound: () => ipcRenderer.sendSync('get-leave-voice-channel-sound'),
    getStartSpeakingSound: () => ipcRenderer.sendSync('get-start-speaking-sound'),
    getStopSpeakingSound: () => ipcRenderer.sendSync('get-stop-speaking-sound'),
    getReceiveDirectMessageSound: () => ipcRenderer.sendSync('get-receive-direct-message-sound'),
    getReceiveChannelMessageSound: () => ipcRenderer.sendSync('get-receive-channel-message-sound'),
    getAutoCheckForUpdates: () => ipcRenderer.sendSync('get-auto-check-for-updates'),
    getUpdateCheckInterval: () => ipcRenderer.sendSync('get-update-check-interval'),
    getUpdateChannel: () => ipcRenderer.sendSync('get-update-channel'),
};

const electronLogHandlers = {
    info: (...messages) => ipcRenderer.send('electron-log-info', messages),
    warn: (...messages) => ipcRenderer.send('electron-log-warn', messages),
    error: (...messages) => ipcRenderer.send('electron-log-error', messages),
};

contextBridge.exposeInMainWorld('ipcRenderer', ipcRendererHandlers);
contextBridge.exposeInMainWorld('electronLog', electronLogHandlers);
