import type * as Types from '@/types';

export interface PopupSizeConfig {
  width: number;
  height: number;
}

export const POPUP_SIZES: Record<Types.PopupType, PopupSizeConfig> = {
  aboutus: { width: 500, height: 750 },
  applyFriend: { width: 490, height: 375 },
  approveFriend: { width: 400, height: 250 },
  applyMember: { width: 490, height: 300 },
  blockMember: { width: 400, height: 250 },
  channelEvent: { width: 500, height: 400 },
  channelSetting: { width: 600, height: 520 },
  channelPassword: { width: 380, height: 200 },
  changeTheme: { width: 480, height: 335 },
  chatHistory: { width: 714, height: 547 },
  createServer: { width: 478, height: 436 },
  createChannel: { width: 380, height: 200 },
  createFriendGroup: { width: 380, height: 200 },
  directMessage: { width: 650, height: 550 },
  dialogAlert: { width: 380, height: 200 },
  dialogAlert2: { width: 380, height: 200 },
  dialogSuccess: { width: 380, height: 200 },
  dialogWarning: { width: 380, height: 200 },
  dialogError: { width: 380, height: 200 },
  dialogInfo: { width: 380, height: 200 },
  editChannelOrder: { width: 500, height: 550 },
  editChannelName: { width: 380, height: 200 },
  editNickname: { width: 380, height: 200 },
  editFriendNote: { width: 380, height: 200 },
  editFriendGroupName: { width: 380, height: 200 },
  friendVerification: { width: 500, height: 550 },
  imageCropper: { width: 610, height: 520 },
  inviteFriend: { width: 490, height: 375 },
  inviteMember: { width: 490, height: 300 },
  kickMemberFromChannel: { width: 400, height: 250 },
  kickMemberFromServer: { width: 400, height: 250 },
  memberApplicationSetting: { width: 380, height: 220 },
  memberInvitation: { width: 500, height: 550 },
  networkDiagnosis: { width: 400, height: 500 },
  rtcDisconnect: { width: 380, height: 200 },
  searchUser: { width: 380, height: 200 },
  serverAnnouncement: { width: 500, height: 400 },
  serverApplication: { width: 320, height: 150 },
  serverSetting: { width: 600, height: 520 },
  serverBroadcast: { width: 450, height: 300 },
  systemSetting: { width: 600, height: 520 },
  userInfo: { width: 440, height: 630 },
  userSetting: { width: 500, height: 700 },
};

export interface PopupHeaderConfig {
  buttons: ('minimize' | 'maxsize' | 'close')[];
  hideHeader: boolean;
}

export const POPUP_HEADERS: Record<Types.PopupType, PopupHeaderConfig> = {
  aboutus: { buttons: ['close'], hideHeader: false },
  applyFriend: { buttons: ['close'], hideHeader: false },
  applyMember: { buttons: ['close'], hideHeader: false },
  approveFriend: { buttons: ['close'], hideHeader: false },
  blockMember: { buttons: ['close'], hideHeader: false },
  channelEvent: { buttons: ['close'], hideHeader: false },
  changeTheme: { buttons: ['close'], hideHeader: false },
  channelPassword: { buttons: ['close'], hideHeader: false },
  channelSetting: { buttons: ['close'], hideHeader: false },
  chatHistory: { buttons: ['close'], hideHeader: false },
  createServer: { buttons: ['close'], hideHeader: false },
  createChannel: { buttons: ['close'], hideHeader: false },
  createFriendGroup: { buttons: ['close'], hideHeader: false },
  dialogAlert: { buttons: ['close'], hideHeader: false },
  dialogAlert2: { buttons: ['close'], hideHeader: false },
  dialogError: { buttons: ['close'], hideHeader: false },
  dialogInfo: { buttons: ['close'], hideHeader: false },
  dialogSuccess: { buttons: ['close'], hideHeader: false },
  dialogWarning: { buttons: ['close'], hideHeader: false },
  directMessage: { buttons: ['close', 'minimize', 'maxsize'], hideHeader: false },
  editChannelOrder: { buttons: ['close'], hideHeader: false },
  editChannelName: { buttons: ['close'], hideHeader: false },
  editFriendNote: { buttons: ['close'], hideHeader: false },
  editFriendGroupName: { buttons: ['close'], hideHeader: false },
  editNickname: { buttons: ['close'], hideHeader: false },
  friendVerification: { buttons: ['close'], hideHeader: false },
  imageCropper: { buttons: ['close'], hideHeader: false },
  inviteFriend: { buttons: ['close'], hideHeader: false },
  inviteMember: { buttons: ['close'], hideHeader: false },
  kickMemberFromChannel: { buttons: ['close'], hideHeader: false },
  kickMemberFromServer: { buttons: ['close'], hideHeader: false },
  memberApplicationSetting: { buttons: ['close'], hideHeader: false },
  memberInvitation: { buttons: ['close'], hideHeader: false },
  networkDiagnosis: { buttons: ['close'], hideHeader: false },
  rtcDisconnect: { buttons: ['close'], hideHeader: false },
  searchUser: { buttons: ['close'], hideHeader: false },
  serverAnnouncement: { buttons: ['close'], hideHeader: true },
  serverApplication: { buttons: ['close'], hideHeader: false },
  serverBroadcast: { buttons: ['close'], hideHeader: false },
  serverSetting: { buttons: ['close'], hideHeader: false },
  systemSetting: { buttons: ['close'], hideHeader: false },
  userInfo: { buttons: ['close'], hideHeader: true },
  userSetting: { buttons: ['close'], hideHeader: false },
};

export const POPUP_TITLE_KEYS: Record<Types.PopupType, string> = {
  aboutus: 'about-ricecall',
  applyFriend: 'apply-friend',
  applyMember: 'apply-member',
  approveFriend: 'approve-friend',
  blockMember: 'block',
  channelEvent: 'channel-event',
  changeTheme: 'change-theme',
  channelPassword: 'please-enter-the-channel-password',
  channelSetting: 'edit-channel',
  chatHistory: 'chat-history',
  createServer: 'create-server',
  createChannel: 'create-channel',
  createFriendGroup: 'create-friend-group',
  dialogAlert: 'alert',
  dialogAlert2: 'alert',
  dialogError: 'error',
  dialogInfo: 'info',
  dialogSuccess: 'success',
  dialogWarning: 'warning',
  directMessage: 'direct-message',
  editChannelOrder: 'edit-channel-order',
  editChannelName: 'edit-channel-name',
  editFriendNote: 'edit-friend-note',
  editFriendGroupName: 'edit-friend-group-name',
  editNickname: 'edit-nickname',
  friendVerification: 'friend-verification',
  imageCropper: 'image-cropper',
  inviteFriend: 'invite-friend',
  inviteMember: 'invite-member',
  kickMemberFromChannel: 'kick-channel',
  kickMemberFromServer: 'kick-server',
  memberApplicationSetting: 'member-application-setting',
  memberInvitation: 'member-invitation',
  networkDiagnosis: 'network-diagnosis',
  rtcDisconnect: 'rtc-disconnect',
  searchUser: 'search-user',
  serverAnnouncement: 'server-announcement',
  serverApplication: 'server-application',
  serverBroadcast: 'server-broadcast',
  serverSetting: 'server-setting',
  systemSetting: 'system-setting',
  userInfo: 'user-info',
  userSetting: 'user-setting',
};

export interface PopupBehaviorConfig {
  resizable: boolean;
  maximizable: boolean;
  fullscreenable: boolean;
}

export const POPUP_BEHAVIORS: Record<Types.PopupType, PopupBehaviorConfig> = {
  aboutus: { resizable: false, maximizable: false, fullscreenable: false },
  applyFriend: { resizable: false, maximizable: false, fullscreenable: false },
  approveFriend: { resizable: false, maximizable: false, fullscreenable: false },
  applyMember: { resizable: false, maximizable: false, fullscreenable: false },
  blockMember: { resizable: false, maximizable: false, fullscreenable: false },
  channelEvent: { resizable: false, maximizable: false, fullscreenable: false },
  channelSetting: { resizable: false, maximizable: false, fullscreenable: false },
  channelPassword: { resizable: false, maximizable: false, fullscreenable: false },
  changeTheme: { resizable: false, maximizable: false, fullscreenable: false },
  chatHistory: { resizable: false, maximizable: false, fullscreenable: false },
  createServer: { resizable: false, maximizable: false, fullscreenable: false },
  createChannel: { resizable: false, maximizable: false, fullscreenable: false },
  createFriendGroup: { resizable: false, maximizable: false, fullscreenable: false },
  directMessage: { resizable: true, maximizable: true, fullscreenable: true },
  dialogAlert: { resizable: false, maximizable: false, fullscreenable: false },
  dialogAlert2: { resizable: false, maximizable: false, fullscreenable: false },
  dialogSuccess: { resizable: false, maximizable: false, fullscreenable: false },
  dialogWarning: { resizable: false, maximizable: false, fullscreenable: false },
  dialogError: { resizable: false, maximizable: false, fullscreenable: false },
  dialogInfo: { resizable: false, maximizable: false, fullscreenable: false },
  editChannelOrder: { resizable: false, maximizable: false, fullscreenable: false },
  editChannelName: { resizable: false, maximizable: false, fullscreenable: false },
  editNickname: { resizable: false, maximizable: false, fullscreenable: false },
  editFriendNote: { resizable: false, maximizable: false, fullscreenable: false },
  editFriendGroupName: { resizable: false, maximizable: false, fullscreenable: false },
  friendVerification: { resizable: false, maximizable: false, fullscreenable: false },
  imageCropper: { resizable: false, maximizable: false, fullscreenable: false },
  inviteFriend: { resizable: false, maximizable: false, fullscreenable: false },
  inviteMember: { resizable: false, maximizable: false, fullscreenable: false },
  kickMemberFromChannel: { resizable: false, maximizable: false, fullscreenable: false },
  kickMemberFromServer: { resizable: false, maximizable: false, fullscreenable: false },
  memberApplicationSetting: { resizable: false, maximizable: false, fullscreenable: false },
  memberInvitation: { resizable: false, maximizable: false, fullscreenable: false },
  networkDiagnosis: { resizable: false, maximizable: false, fullscreenable: false },
  rtcDisconnect: { resizable: false, maximizable: false, fullscreenable: false },
  searchUser: { resizable: false, maximizable: false, fullscreenable: false },
  serverAnnouncement: { resizable: false, maximizable: false, fullscreenable: false },
  serverApplication: { resizable: false, maximizable: false, fullscreenable: false },
  serverSetting: { resizable: false, maximizable: false, fullscreenable: false },
  serverBroadcast: { resizable: false, maximizable: false, fullscreenable: false },
  systemSetting: { resizable: false, maximizable: false, fullscreenable: false },
  userInfo: { resizable: false, maximizable: false, fullscreenable: false },
  userSetting: { resizable: false, maximizable: false, fullscreenable: false },
};

interface PopupConfig {
  size: PopupSizeConfig;
  title: string;
  buttons: ('close' | 'minimize' | 'maxsize')[];
  hideHeader: boolean;
  resizable: boolean;
  maximizable: boolean;
  fullscreenable: boolean;
}

export const POPUP_CONFIGS: Record<Types.PopupType, PopupConfig> = {
  aboutus: {
    size: POPUP_SIZES.aboutus,
    title: POPUP_TITLE_KEYS.aboutus,
    ...POPUP_HEADERS.aboutus,
    ...POPUP_BEHAVIORS.aboutus,
  },
  applyFriend: {
    size: POPUP_SIZES.applyFriend,
    title: POPUP_TITLE_KEYS.applyFriend,
    ...POPUP_HEADERS.applyFriend,
    ...POPUP_BEHAVIORS.applyFriend,
  },
  applyMember: {
    size: POPUP_SIZES.applyMember,
    title: POPUP_TITLE_KEYS.applyMember,
    ...POPUP_HEADERS.applyMember,
    ...POPUP_BEHAVIORS.applyMember,
  },
  approveFriend: {
    size: POPUP_SIZES.approveFriend,
    title: POPUP_TITLE_KEYS.approveFriend,
    ...POPUP_HEADERS.approveFriend,
    ...POPUP_BEHAVIORS.approveFriend,
  },
  blockMember: {
    size: POPUP_SIZES.blockMember,
    title: POPUP_TITLE_KEYS.blockMember,
    ...POPUP_HEADERS.blockMember,
    ...POPUP_BEHAVIORS.blockMember,
  },
  channelEvent: {
    size: POPUP_SIZES.channelEvent,
    title: POPUP_TITLE_KEYS.channelEvent,
    ...POPUP_HEADERS.channelEvent,
    ...POPUP_BEHAVIORS.channelEvent,
  },
  channelPassword: {
    size: POPUP_SIZES.channelPassword,
    title: POPUP_TITLE_KEYS.channelPassword,
    ...POPUP_HEADERS.channelPassword,
    ...POPUP_BEHAVIORS.channelPassword,
  },
  channelSetting: {
    size: POPUP_SIZES.channelSetting,
    title: POPUP_TITLE_KEYS.channelSetting,
    ...POPUP_HEADERS.channelSetting,
    ...POPUP_BEHAVIORS.channelSetting,
  },
  changeTheme: {
    size: POPUP_SIZES.changeTheme,
    title: POPUP_TITLE_KEYS.changeTheme,
    ...POPUP_HEADERS.changeTheme,
    ...POPUP_BEHAVIORS.changeTheme,
  },
  chatHistory: {
    size: POPUP_SIZES.chatHistory,
    title: POPUP_TITLE_KEYS.chatHistory,
    ...POPUP_HEADERS.chatHistory,
    ...POPUP_BEHAVIORS.chatHistory,
  },
  createServer: {
    size: POPUP_SIZES.createServer,
    title: POPUP_TITLE_KEYS.createServer,
    ...POPUP_HEADERS.createServer,
    ...POPUP_BEHAVIORS.createServer,
  },
  createChannel: {
    size: POPUP_SIZES.createChannel,
    title: POPUP_TITLE_KEYS.createChannel,
    ...POPUP_HEADERS.createChannel,
    ...POPUP_BEHAVIORS.createChannel,
  },
  createFriendGroup: {
    size: POPUP_SIZES.createFriendGroup,
    title: POPUP_TITLE_KEYS.createFriendGroup,
    ...POPUP_HEADERS.createFriendGroup,
    ...POPUP_BEHAVIORS.createFriendGroup,
  },
  dialogAlert: {
    size: POPUP_SIZES.dialogAlert,
    title: POPUP_TITLE_KEYS.dialogAlert,
    ...POPUP_HEADERS.dialogAlert,
    ...POPUP_BEHAVIORS.dialogAlert,
  },
  dialogAlert2: {
    size: POPUP_SIZES.dialogAlert2,
    title: POPUP_TITLE_KEYS.dialogAlert2,
    ...POPUP_HEADERS.dialogAlert2,
    ...POPUP_BEHAVIORS.dialogAlert2,
  },
  dialogError: {
    size: POPUP_SIZES.dialogError,
    title: POPUP_TITLE_KEYS.dialogError,
    ...POPUP_HEADERS.dialogError,
    ...POPUP_BEHAVIORS.dialogError,
  },
  dialogInfo: {
    size: POPUP_SIZES.dialogInfo,
    title: POPUP_TITLE_KEYS.dialogInfo,
    ...POPUP_HEADERS.dialogInfo,
    ...POPUP_BEHAVIORS.dialogInfo,
  },
  dialogSuccess: {
    size: POPUP_SIZES.dialogSuccess,
    title: POPUP_TITLE_KEYS.dialogSuccess,
    ...POPUP_HEADERS.dialogSuccess,
    ...POPUP_BEHAVIORS.dialogSuccess,
  },
  dialogWarning: {
    size: POPUP_SIZES.dialogWarning,
    title: POPUP_TITLE_KEYS.dialogWarning,
    ...POPUP_HEADERS.dialogWarning,
    ...POPUP_BEHAVIORS.dialogWarning,
  },
  directMessage: {
    size: POPUP_SIZES.directMessage,
    title: POPUP_TITLE_KEYS.directMessage,
    ...POPUP_HEADERS.directMessage,
    ...POPUP_BEHAVIORS.directMessage,
  },
  editChannelOrder: {
    size: POPUP_SIZES.editChannelOrder,
    title: POPUP_TITLE_KEYS.editChannelOrder,
    ...POPUP_HEADERS.editChannelOrder,
    ...POPUP_BEHAVIORS.editChannelOrder,
  },
  editChannelName: {
    size: POPUP_SIZES.editChannelName,
    title: POPUP_TITLE_KEYS.editChannelName,
    ...POPUP_HEADERS.editChannelName,
    ...POPUP_BEHAVIORS.editChannelName,
  },
  editFriendNote: {
    size: POPUP_SIZES.editFriendNote,
    title: POPUP_TITLE_KEYS.editFriendNote,
    ...POPUP_HEADERS.editFriendNote,
    ...POPUP_BEHAVIORS.editFriendNote,
  },
  editFriendGroupName: {
    size: POPUP_SIZES.editFriendGroupName,
    title: POPUP_TITLE_KEYS.editFriendGroupName,
    ...POPUP_HEADERS.editFriendGroupName,
    ...POPUP_BEHAVIORS.editFriendGroupName,
  },
  editNickname: {
    size: POPUP_SIZES.editNickname,
    title: POPUP_TITLE_KEYS.editNickname,
    ...POPUP_HEADERS.editNickname,
    ...POPUP_BEHAVIORS.editNickname,
  },
  friendVerification: {
    size: POPUP_SIZES.friendVerification,
    title: POPUP_TITLE_KEYS.friendVerification,
    ...POPUP_HEADERS.friendVerification,
    ...POPUP_BEHAVIORS.friendVerification,
  },
  imageCropper: {
    size: POPUP_SIZES.imageCropper,
    title: POPUP_TITLE_KEYS.imageCropper,
    ...POPUP_HEADERS.imageCropper,
    ...POPUP_BEHAVIORS.imageCropper,
  },
  inviteFriend: {
    size: POPUP_SIZES.inviteFriend,
    title: POPUP_TITLE_KEYS.inviteFriend,
    ...POPUP_HEADERS.inviteFriend,
    ...POPUP_BEHAVIORS.inviteFriend,
  },
  inviteMember: {
    size: POPUP_SIZES.inviteMember,
    title: POPUP_TITLE_KEYS.inviteMember,
    ...POPUP_HEADERS.inviteMember,
    ...POPUP_BEHAVIORS.inviteMember,
  },
  kickMemberFromChannel: {
    size: POPUP_SIZES.kickMemberFromChannel,
    title: POPUP_TITLE_KEYS.kickMemberFromChannel,
    ...POPUP_HEADERS.kickMemberFromChannel,
    ...POPUP_BEHAVIORS.kickMemberFromChannel,
  },
  kickMemberFromServer: {
    size: POPUP_SIZES.kickMemberFromServer,
    title: POPUP_TITLE_KEYS.kickMemberFromServer,
    ...POPUP_HEADERS.kickMemberFromServer,
    ...POPUP_BEHAVIORS.kickMemberFromServer,
  },
  memberApplicationSetting: {
    size: POPUP_SIZES.memberApplicationSetting,
    title: POPUP_TITLE_KEYS.memberApplicationSetting,
    ...POPUP_HEADERS.memberApplicationSetting,
    ...POPUP_BEHAVIORS.memberApplicationSetting,
  },
  memberInvitation: {
    size: POPUP_SIZES.memberInvitation,
    title: POPUP_TITLE_KEYS.memberInvitation,
    ...POPUP_HEADERS.memberInvitation,
    ...POPUP_BEHAVIORS.memberInvitation,
  },
  networkDiagnosis: {
    size: POPUP_SIZES.networkDiagnosis,
    title: POPUP_TITLE_KEYS.networkDiagnosis,
    ...POPUP_HEADERS.networkDiagnosis,
    ...POPUP_BEHAVIORS.networkDiagnosis,
  },
  rtcDisconnect: {
    size: POPUP_SIZES.rtcDisconnect,
    title: POPUP_TITLE_KEYS.rtcDisconnect,
    ...POPUP_HEADERS.rtcDisconnect,
    ...POPUP_BEHAVIORS.rtcDisconnect,
  },
  searchUser: {
    size: POPUP_SIZES.searchUser,
    title: POPUP_TITLE_KEYS.searchUser,
    ...POPUP_HEADERS.searchUser,
    ...POPUP_BEHAVIORS.searchUser,
  },
  serverAnnouncement: {
    size: POPUP_SIZES.serverAnnouncement,
    title: POPUP_TITLE_KEYS.serverAnnouncement,
    ...POPUP_HEADERS.serverAnnouncement,
    ...POPUP_BEHAVIORS.serverAnnouncement,
  },
  serverApplication: {
    size: POPUP_SIZES.serverApplication,
    title: POPUP_TITLE_KEYS.serverApplication,
    ...POPUP_HEADERS.serverApplication,
    ...POPUP_BEHAVIORS.serverApplication,
  },
  serverBroadcast: {
    size: POPUP_SIZES.serverBroadcast,
    title: POPUP_TITLE_KEYS.serverBroadcast,
    ...POPUP_HEADERS.serverBroadcast,
    ...POPUP_BEHAVIORS.serverBroadcast,
  },
  serverSetting: {
    size: POPUP_SIZES.serverSetting,
    title: POPUP_TITLE_KEYS.serverSetting,
    ...POPUP_HEADERS.serverSetting,
    ...POPUP_BEHAVIORS.serverSetting,
  },
  systemSetting: {
    size: POPUP_SIZES.systemSetting,
    title: POPUP_TITLE_KEYS.systemSetting,
    ...POPUP_HEADERS.systemSetting,
    ...POPUP_BEHAVIORS.systemSetting,
  },
  userInfo: {
    size: POPUP_SIZES.userInfo,
    title: POPUP_TITLE_KEYS.userInfo,
    ...POPUP_HEADERS.userInfo,
    ...POPUP_BEHAVIORS.userInfo,
  },
  userSetting: {
    size: POPUP_SIZES.userSetting,
    title: POPUP_TITLE_KEYS.userSetting,
    ...POPUP_HEADERS.userSetting,
    ...POPUP_BEHAVIORS.userSetting,
  },
};
