/* eslint-disable @typescript-eslint/no-explicit-any */
import type * as Types from '@/types';

export type eventEmitterHandlers = {
  send: (channel: string, ...args: unknown[]) => void;
  sendSync: <T = any>(channel: string, ...args: unknown[]) => T;
  invoke: <T = any>(channel: string, ...args: unknown[]) => Promise<T>;
  removeAllListeners: (channel: string) => void;
};

export type ElectronLogHandlers = {
  info: (...messages: string[]) => void;
  warn: (...messages: string[]) => void;
  error: (...messages: string[]) => void;
};

export type IpcRendererHandlers = {
  eventEmitter: eventEmitterHandlers;
  listen: (channel: string, listener: (...args: any[]) => void) => () => void;
  socketSend: <T extends keyof Types.ClientToServerEvents>(event: T, ...args: Parameters<Types.ClientToServerEvents[T]>) => void;
  socketEmit: <T extends keyof Types.ClientToServerEventsWithAck>(
    event: T,
    payload: Parameters<Types.ClientToServerEventsWithAck[T]>[0],
  ) => Promise<ACK<ReturnType<Types.ClientToServerEventsWithAck[T]>>>;
  getInitialData: (id: string) => unknown | null;
  errorSubmit: (errorId: string, error: Error) => void;
  exit: () => void;
  windowMinimize: (popupId?: string) => void;
  windowMaximize: () => void;
  windowUnmaximize: () => void;
  windowClose: () => void;
  openPopup: (type: Types.PopupType, id: string, initialData: unknown, force?: boolean) => void;
  closePopup: (id: string) => void;
  closeAllPopups: () => void;
  popupSubmit: (to: string, data?: unknown) => void;
  addAccount: (account: string, data: { autoLogin: boolean; rememberAccount: boolean; password: string }) => void;
  deleteAccount: (account: string) => void;
  setLanguage: (language: Types.LanguageKey) => void;
  addCustomTheme: (theme: Types.Theme) => void;
  deleteCustomTheme: (index: number) => void;
  setCurrentTheme: (theme: Types.Theme | null) => void;
  updateDiscordPresence: (presence: Types.DiscordPresence) => void;
  saveRecord: (record: ArrayBuffer) => void;
  setTrayTitle: (title: string) => void;
  dontShowDisclaimerNextTime: () => void;
  checkForUpdates: () => void;
  changeEnv: (server: 'prod' | 'dev') => void;
  setAutoLogin: (enable: boolean) => void;
  setAutoLaunch: (enable: boolean) => void;
  setAlwaysOnTop: (enable: boolean) => void;
  setStatusAutoIdle: (enable: boolean) => void;
  setStatusAutoIdleMinutes: (minutes: number) => void;
  setStatusAutoDnd: (enable: boolean) => void;
  setChannelUIMode: (mode: Types.ChannelUIMode) => void;
  setCloseToTray: (enable: boolean) => void;
  setFont: (font: string) => void;
  setFontSize: (fontSize: number) => void;
  setInputAudioDevice: (deviceId: string) => void;
  setOutputAudioDevice: (deviceId: string) => void;
  setRecordFormat: (format: Types.RecordFormat) => void;
  setRecordSavePath: (path: string) => void;
  setMixEffect: (enabled: boolean) => void;
  setMixEffectType: (key: string) => void;
  setAutoMixSetting: (enabled: boolean) => void;
  setEchoCancellation: (enabled: boolean) => void;
  setNoiseCancellation: (enabled: boolean) => void;
  setMicrophoneAmplification: (enabled: boolean) => void;
  setManualMixMode: (enabled: boolean) => void;
  setMixMode: (key: Types.MixMode) => void;
  setSpeakingMode: (key: Types.SpeakingMode) => void;
  setDefaultSpeakingKey: (key: string) => void;
  setNotSaveMessageHistory: (enabled: boolean) => void;
  setHotKeyOpenMainWindow: (key: string) => void;
  setHotKeyIncreaseVolume: (key: string) => void;
  setHotKeyDecreaseVolume: (key: string) => void;
  setHotKeyToggleSpeaker: (key: string) => void;
  setHotKeyToggleMicrophone: (key: string) => void;
  setDisableAllSoundEffect: (enabled: boolean) => void;
  setEnterVoiceChannelSound: (enabled: boolean) => void;
  setLeaveVoiceChannelSound: (enabled: boolean) => void;
  setStartSpeakingSound: (enabled: boolean) => void;
  setStopSpeakingSound: (enabled: boolean) => void;
  setReceiveDirectMessageSound: (enabled: boolean) => void;
  setReceiveChannelMessageSound: (enabled: boolean) => void;
  setAutoCheckForUpdates: (enabled: boolean) => void;
  setUpdateCheckInterval: (interval: number) => void;
  setUpdateChannel: (channel: string) => void;
  runNetworkDiagnosis: (params: { domains: string[]; duration?: number }) => Promise<Types.FullReport | { error: string }>;
  cancelNetworkDiagnosis: () => void;
  requestSfuDiagnosis: () => void;
  sfuDiagnosisResponse: (info: Types.SFUDiagnosisInfo | null) => void;
  login: (formData: { account: string; password: string }) => Promise<{ success: true; token: string } | { success: false }>;
  logout: () => Promise<void>;
  register: (formData: { account: string; password: string; email: string; username: string; locale: string }) => Promise<{ success: true; message: string } | { success: false }>;
  autoLogin: (token: string) => Promise<{ success: true; token: string } | { success: false }>;
  dataUser: (params: { userId: string }) => Promise<Types.User | null>;
  dataUserHotReload: (params: { userId: string }) => Promise<Types.User | null>;
  dataFriend: (params: { userId: string; targetId: string }) => Promise<Types.Friend | null>;
  dataFriends: (params: { userId: string }) => Promise<Types.Friend[]>;
  dataFriendActivities: (params: { userId: string }) => Promise<Types.FriendActivity[]>;
  dataFriendGroup: (params: { userId: string; friendGroupId: string }) => Promise<Types.FriendGroup | null>;
  dataFriendGroups: (params: { userId: string }) => Promise<Types.FriendGroup[]>;
  dataFriendApplication: (params: { receiverId: string; senderId: string }) => Promise<Types.FriendApplication | null>;
  dataFriendApplications: (params: { receiverId: string }) => Promise<Types.FriendApplication[]>;
  dataServer: (params: { userId: string; serverId: string }) => Promise<Types.Server | null>;
  dataServers: (params: { userId: string }) => Promise<Types.Server[]>;
  dataServerMembers: (params: { serverId: string }) => Promise<Types.Member[]>;
  dataServerOnlineMembers: (params: { serverId: string }) => Promise<Types.OnlineMember[]>;
  dataChannel: (params: { userId: string; serverId: string; channelId: string }) => Promise<Types.Channel | null>;
  dataChannels: (params: { userId: string; serverId: string }) => Promise<Types.Channel[]>;
  dataChannelMembers: (params: { serverId: string; channelId: string }) => Promise<Types.Member[]>;
  dataMember: (params: { userId: string; serverId: string; channelId?: string }) => Promise<Types.Member | null>;
  dataMemberApplication: (params: { userId: string; serverId: string }) => Promise<Types.MemberApplication | null>;
  dataMemberApplications: (params: { serverId: string }) => Promise<Types.MemberApplication[]>;
  dataMemberInvitation: (params: { receiverId: string; serverId: string }) => Promise<Types.MemberInvitation | null>;
  dataMemberInvitations: (params: { receiverId: string }) => Promise<Types.MemberInvitation[]>;
  dataNotifications: (params: { region: Types.LanguageKey }) => Promise<Types.Notification[]>;
  dataAnnouncements: (params: { region: Types.LanguageKey }) => Promise<Types.Announcement[]>;
  dataRecommendServers: (params: { region: Types.LanguageKey }) => Promise<Types.RecommendServer[]>;
  dataUploadImage: (params: { folder: string; imageName: string; imageUnit8Array: Uint8Array }) => Promise<{ imageName: string; imageUrl: string } | null>;
  dataSearchServer: (params: { query: string }) => Promise<Types.Server[]>;
  dataSearchUser: (params: { query: string }) => Promise<Types.User[]>;
  saveImage: (buffer: ArrayBuffer, directory: string, filenamePrefix: string, extension: string) => Promise<string | null>;
  selectRecordSavePath: () => Promise<string | null>;
  enableLoopbackAudio: () => Promise<void>;
  disableLoopbackAudio: () => Promise<void>;
  getAccounts: () => Record<string, { autoLogin: boolean; rememberAccount: boolean; password: string }>;
  getLanguage: () => Types.LanguageKey;
  getCustomThemes: () => Types.Theme[];
  getCurrentTheme: () => Types.Theme | null;
  getFontList: () => string[];
  getSystemSettings: () => Types.SystemSettings | null;
  getAutoLogin: () => boolean;
  getAutoLaunch: () => boolean;
  getAlwaysOnTop: () => boolean;
  getStatusAutoIdle: () => boolean;
  getStatusAutoIdleMinutes: () => number;
  getStatusAutoDnd: () => boolean;
  getChannelUIMode: () => Types.ChannelUIMode;
  getCloseToTray: () => boolean;
  getFont: () => string;
  getFontSize: () => number;
  getInputAudioDevice: () => string;
  getOutputAudioDevice: () => string;
  getRecordFormat: () => Types.RecordFormat;
  getRecordSavePath: () => string;
  getMixEffect: () => boolean;
  getMixEffectType: () => string;
  getAutoMixSetting: () => boolean;
  getEchoCancellation: () => boolean;
  getNoiseCancellation: () => boolean;
  getMicrophoneAmplification: () => boolean;
  getManualMixMode: () => boolean;
  getMixMode: () => Types.MixMode;
  getSpeakingMode: () => Types.SpeakingMode;
  getDefaultSpeakingKey: () => string;
  getNotSaveMessageHistory: () => boolean;
  getHotKeyOpenMainWindow: () => string;
  getHotKeyIncreaseVolume: () => string;
  getHotKeyDecreaseVolume: () => string;
  getHotKeyToggleSpeaker: () => string;
  getHotKeyToggleMicrophone: () => string;
  getDisableAllSoundEffect: () => boolean;
  getEnterVoiceChannelSound: () => boolean;
  getLeaveVoiceChannelSound: () => boolean;
  getStartSpeakingSound: () => boolean;
  getStopSpeakingSound: () => boolean;
  getReceiveDirectMessageSound: () => boolean;
  getReceiveChannelMessageSound: () => boolean;
  getAutoCheckForUpdates: () => boolean;
  getUpdateCheckInterval: () => number;
  getUpdateChannel: () => string;
  serverSelect: (data: { serverDisplayId: Types.Server['displayId']; serverId: Types.Server['serverId']; timestamp: number }) => void;
  webRTCSignalStateChange: (formData: { signalState: string; userId: string; channelId: string; info?: any }) => void;
};

declare global {
  interface Window {
    ipcRenderer?: IpcRendererHandlers;
    electronLog?: ElectronLogHandlers;
  }
}
