import { User, Channel, Server, Member, Friend, FriendGroup, FriendApplication, MemberApplication, MemberInvitation } from '@/types';

const Default = {
  user: (overrides: Partial<User> = {}): User => ({
    userId: '',
    name: '',
    displayId: '',
    avatar: `${Date.now()}`,
    avatarUrl: `/default/userAvatar.webp`,
    email: '',
    signature: '',
    about: '',
    status: 'online',
    gender: 'Male',
    birthYear: new Date().getFullYear() - 20,
    birthMonth: 1,
    birthDay: 1,
    country: 'taiwan',
    level: 0,
    vip: 0,
    vxp: 0,
    xp: 0,
    requiredXp: 0,
    permissionLevel: 1,
    currentChannelId: null,
    currentServerId: null,
    lastActiveAt: 0,
    createdAt: 0,
    badges: '[]',
    ...overrides,
  }),

  friend: (overrides: Partial<Friend> = {}): Friend => ({
    ...Default.user(),
    userId: '',
    targetId: '',
    note: '',
    relationStatus: 0,
    isBlocked: false,
    friendGroupId: '',
    createdAt: 0,
    ...overrides,
  }),

  friendGroup: (overrides: Partial<FriendGroup> = {}): FriendGroup => ({
    friendGroupId: '',
    userId: '',
    name: '',
    order: 0,
    createdAt: 0,
    ...overrides,
  }),

  friendApplication: (overrides: Partial<FriendApplication> = {}): FriendApplication => ({
    ...Default.user(),
    senderId: '',
    receiverId: '',
    description: '',
    createdAt: 0,
    ...overrides,
  }),

  server: (overrides: Partial<Server> = {}): Server => ({
    serverId: '',
    userId: '',
    name: '',
    nickname: null,
    avatar: `${Date.now()}`,
    avatarUrl: `/default/serverAvatar.webp`,
    announcement: '',
    applyNotice: '',
    description: '',
    slogan: '',
    type: 'other',
    visibility: 'public',
    receiveApply: true,
    permissionLevel: 1,
    contribution: 0,
    level: 0,
    wealth: 0,
    displayId: '',
    lobbyId: '',
    receptionLobbyId: '',
    ownerId: '',
    createdAt: 0,
    recent: false,
    owned: false,
    favorite: false,
    timestamp: 0,
    ...overrides,
  }),

  channel: (overrides: Partial<Channel> = {}): Channel => ({
    channelId: '',
    userId: '',
    name: '',
    announcement: '',
    type: 'channel',
    visibility: 'public',
    password: '',
    voiceMode: 'free',
    isLobby: false,
    isTextMuted: false,
    isVoiceMuted: false,
    forbidText: false,
    forbidQueue: false,
    forbidGuestText: false,
    forbidGuestVoice: false,
    forbidGuestQueue: false,
    forbidGuestUrl: false,
    guestTextMaxLength: 2000,
    guestTextWaitTime: 0,
    guestTextGapTime: 0,
    bitrate: 64000,
    userLimit: 0,
    order: 0,
    permissionLevel: 1,
    serverId: '',
    categoryId: '',
    createdAt: 0,
    ...overrides,
  }),

  member: (overrides: Partial<Member> = {}): Member => ({
    ...Default.user(),
    userId: '',
    serverId: '',
    nickname: null,
    contribution: 0,
    blockedUntil: 0,
    createdAt: 0,
    ...overrides,
  }),

  memberApplication: (overrides: Partial<MemberApplication> = {}): MemberApplication => ({
    ...Default.user(),
    serverId: '',
    description: '',
    createdAt: 0,
    ...overrides,
  }),

  memberInvitation: (overrides: Partial<MemberInvitation> = {}): MemberInvitation => ({
    ...Default.user(),
    receiverId: '',
    serverId: '',
    description: '',
    createdAt: 0,
    ...overrides,
  }),
};

export default Default;
