#!/usr/bin/env node
/**
 * Popup Code Generator
 * 
 * This script reads popup.config.ts and generates component imports and mappings.
 * 
 * Usage: npx tsx scripts/generate-popup-imports.ts
 * 
 * Or add to package.json:
 * "scripts": {
 *   "generate:popups": "tsx scripts/generate-popup-imports.ts"
 * }
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// We need to parse the config file since it's TypeScript
const configPath = path.join(__dirname, '..', 'src', 'popup.config.ts');
const configContent = fs.readFileSync(configPath, 'utf-8');

// Extract component names from the config
const componentRegex = /component:\s*['"]([^'"]+)['"]/g;
const componentNames = new Set<string>();

let match;
while ((match = componentRegex.exec(configContent)) !== null) {
  componentNames.add(match[1]);
}

const sortedComponents = Array.from(componentNames).sort();

// Generate output
const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * Generated by: npm run generate:popups
 * Source: src/popup.config.ts
 * 
 * This file contains all popup component imports and mappings for the web version.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';

// ============================================================================
// Popup Component Imports
// ============================================================================

${sortedComponents.map(name => `import ${name} from '@/popups/${name}';`).join('\n')}

// ============================================================================
// Component Registry
// ============================================================================

export const POPUP_COMPONENTS: Record<string, React.ComponentType<any>> = {
${sortedComponents.map(name => `  ${name},`).join('\n')}
};

/**
 * Get a popup component by name
 */
export function getPopupComponent(componentName: string): React.ComponentType<any> | null {
  return POPUP_COMPONENTS[componentName] ?? null;
}
`;

// Write to file
const outputPath = path.join(__dirname, '..', 'src', 'platform', 'popup', 'popupComponents.generated.tsx');
fs.writeFileSync(outputPath, output, 'utf-8');

console.log(`✅ Generated ${outputPath}`);
console.log(`   - ${sortedComponents.length} unique components`);
console.log('');
console.log('Components:');
sortedComponents.forEach(name => console.log(`   - ${name}`));
