/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * Generated by: npm run generate:popups
 * Source: src/popup.config.ts
 * 
 * This file contains all popup component imports and mappings for the web version.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import type * as Types from '@/types';

// ============================================================================
// Popup Component Imports
// ============================================================================

import About from '@/popups/About';
import ApplyFriend from '@/popups/ApplyFriend';
import ApplyMember from '@/popups/ApplyMember';
import ApproveFriend from '@/popups/ApproveFriend';
import BlockMember from '@/popups/BlockMember';
import ChangeTheme from '@/popups/ChangeTheme';
import ChannelEvent from '@/popups/ChannelEvent';
import ChannelPassword from '@/popups/ChannelPassword';
import ChannelSetting from '@/popups/ChannelSetting';
import ChatHistory from '@/popups/ChatHistory';
import CreateChannel from '@/popups/CreateChannel';
import CreateFriendGroup from '@/popups/CreateFriendGroup';
import CreateServer from '@/popups/CreateServer';
import Dialog from '@/popups/Dialog';
import DirectMessage from '@/popups/DirectMessage';
import EditChannelName from '@/popups/EditChannelName';
import EditChannelOrder from '@/popups/EditChannelOrder';
import EditFriendGroupName from '@/popups/EditFriendGroupName';
import EditFriendNote from '@/popups/EditFriendNote';
import EditNickname from '@/popups/EditNickname';
import FriendVerification from '@/popups/FriendVerification';
import ImageCropper from '@/popups/ImageCropper';
import InviteFriend from '@/popups/InviteFriend';
import InviteMember from '@/popups/InviteMember';
import KickMemberFromChannel from '@/popups/KickMemberFromChannel';
import KickMemberFromServer from '@/popups/KickMemberFromServer';
import MemberApplicationSetting from '@/popups/MemberApplicationSetting';
import MemberInvitation from '@/popups/MemberInvitation';
import SearchUser from '@/popups/SearchUser';
import ServerAnnouncement from '@/popups/ServerAnnouncement';
import ServerApplication from '@/popups/ServerApplication';
import ServerBroadcast from '@/popups/ServerBroadcast';
import ServerSetting from '@/popups/ServerSetting';
import SystemSetting from '@/popups/SystemSetting';
import UserInfo from '@/popups/UserInfo';

// ============================================================================
// Component Registry by Name
// ============================================================================

export const POPUP_COMPONENTS: Record<string, React.ComponentType<any>> = {
  About,
  ApplyFriend,
  ApplyMember,
  ApproveFriend,
  BlockMember,
  ChangeTheme,
  ChannelEvent,
  ChannelPassword,
  ChannelSetting,
  ChatHistory,
  CreateChannel,
  CreateFriendGroup,
  CreateServer,
  Dialog,
  DirectMessage,
  EditChannelName,
  EditChannelOrder,
  EditFriendGroupName,
  EditFriendNote,
  EditNickname,
  FriendVerification,
  ImageCropper,
  InviteMember,
  KickMemberFromChannel,
  KickMemberFromServer,
  MemberApplicationSetting,
  MemberInvitation,
  SearchUser,
  ServerApplication,
  ServerBroadcast,
  ServerSetting,
  SystemSetting,
  UserInfo,
};

// ============================================================================
// Popup Type to Component Mapping
// ============================================================================

/**
 * Maps popup types to their React components.
 * Dialog types share the same component but with different iconType props.
 */
export const PopupComponentMap: Record<Types.PopupType, React.ComponentType<any>> = {
  aboutus: About,
  applyFriend: ApplyFriend,
  applyMember: ApplyMember,
  approveFriend: ApproveFriend,
  blockMember: BlockMember,
  channelEvent: ChannelEvent,
  changeTheme: ChangeTheme,
  channelPassword: ChannelPassword,
  channelSetting: ChannelSetting,
  chatHistory: ChatHistory,
  createChannel: CreateChannel,
  createFriendGroup: CreateFriendGroup,
  createServer: CreateServer,
  dialogAlert: Dialog,
  dialogAlert2: Dialog,
  dialogError: Dialog,
  dialogInfo: Dialog,
  dialogSuccess: Dialog,
  dialogWarning: Dialog,
  directMessage: DirectMessage,
  editChannelName: EditChannelName,
  editChannelOrder: EditChannelOrder,
  editFriendGroupName: EditFriendGroupName,
  editFriendNote: EditFriendNote,
  editNickname: EditNickname,
  friendVerification: FriendVerification,
  imageCropper: ImageCropper,
  inviteFriend: InviteFriend,
  inviteMember: InviteMember,
  kickMemberFromChannel: KickMemberFromChannel,
  kickMemberFromServer: KickMemberFromServer,
  memberApplicationSetting: MemberApplicationSetting,
  memberInvitation: MemberInvitation,
  searchUser: SearchUser,
  serverAnnouncement: ServerAnnouncement,
  serverApplication: ServerApplication,
  serverBroadcast: ServerBroadcast,
  serverSetting: ServerSetting,
  systemSetting: SystemSetting,
  userInfo: UserInfo,
  userSetting: UserInfo, // UserSetting uses UserInfo component
};

/**
 * Get extra props for specific popup types (e.g., Dialog iconType)
 */
export function getPopupExtraProps(type: Types.PopupType): Record<string, any> {
  switch (type) {
    case 'dialogAlert':
    case 'dialogAlert2':
      return { iconType: 'ALERT' };
    case 'dialogError':
      return { iconType: 'ERROR' };
    case 'dialogInfo':
      return { iconType: 'INFO' };
    case 'dialogSuccess':
      return { iconType: 'SUCCESS' };
    case 'dialogWarning':
      return { iconType: 'WARNING' };
    default:
      return {};
  }
}

/**
 * Get a popup component by name
 */
export function getPopupComponent(componentName: string): React.ComponentType<any> | null {
  return POPUP_COMPONENTS[componentName] ?? null;
}

/**
 * Render a popup by type
 */
export function renderPopup(type: Types.PopupType, id: string, data: any): React.ReactNode {
  const Component = PopupComponentMap[type];
  if (!Component) return null;
  const extraProps = getPopupExtraProps(type);
  return <Component id={id} {...data} {...extraProps} />;
}
