on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: rc-client:latest
          outputs: type=docker,dest=/tmp/rc-client.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rc-client
          path: /tmp/rc-client.tar

  client-use:
    runs-on: ubuntu-latest
    needs: client-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rc-client
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/rc-client.tar
          docker image ls -a

      - name: Run the image
        run: |
          docker run -d -p 3000:3000 --name rc-client rc-client:latest
          docker ps -a

      - name: Check port mapping
        run: |
          docker port rc-client
          sleep 5
          docker logs rc-client
          curl http://localhost:3000